//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Periodico2.Persistencia.Conexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTOR
    {
        public AUTOR()
        {
            this.NOTICIA = new HashSet<NOTICIA>();
        }
    
        public int ID_AUTOR { get; set; }
        public string NOMBRE { get; set; }
        public string FOTO { get; set; }
        public string TITULO { get; set; }
    
        public virtual ICollection<NOTICIA> NOTICIA { get; set; }
    }
}
